name: somnotate-vlkuzun
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy<1.25.0
  - matplotlib
  - scikit-learn
  - pyedflib
  - lspopt
  - h5py
  - pandas
  - seaborn
  - statsmodels
  - pip
  - pip:
      - brokenaxes
      - pomegranate<1.0.0
